// Volunteers Actions

export const GET_VOLUNTEER_LIST = 'GET_VOLUNTEER_LIST';
export const GET_VOLUNTEER = 'GET_VOLUNTEER';

export const VOLUNTEERS_CALL_REQUEST = 'VOLUNTEERS_CALL_REQUEST';
export const VOLUNTEERS_CALL_SUCCESS = 'VOLUNTEERS_CALL_SUCCESS';
export const VOLUNTEERS_CALL_FAILURE = 'VOLUNTEERS_CALL_FAILURE';
