// Volunteers Actions
export const GET_VOLUNTEER_LIST = 'GET_VOLUNTEER_LIST';
export const GET_VOLUNTEER = 'GET_VOLUNTEER';

export const VOLUNTEERS_CALL_REQUEST = 'VOLUNTEERS_CALL_REQUEST';
export const VOLUNTEERS_CALL_SUCCESS = 'VOLUNTEERS_CALL_SUCCESS';
export const VOLUNTEERS_CALL_FAILURE = 'VOLUNTEERS_CALL_FAILURE';

export const VOLUNTEER_CALL_REQUEST = 'VOLUNTEER_CALL_REQUEST';
export const VOLUNTEER_CALL_SUCCESS = 'VOLUNTEER_CALL_SUCCESS';
export const VOLUNTEER_CALL_FAILURE = 'VOLUNTEER_CALL_FAILURE';

//Events actions
export const EVENTS_CALL_REQUEST = 'EVENTS_CALL_REQUEST';
export const EVENTS_CALL_SUCCESS = 'EVENTS_CALL_SUCCESS';
export const EVENTS_CALL_FAILURE = 'EVENTS_CALL_FAILURE';

export const EVENT_CALL_REQUEST = 'EVENTS_CALL_REQUEST';
export const EVENT_CALL_SUCCESS = 'EVENTS_CALL_SUCCESS';
export const EVENT_CALL_FAILURE = 'EVENTS_CALL_FAILURE';

export const VOLUNTEER_USER_CALL_FAILURE = 'VOLUNTEER_USER_CALL_FAILURE';
export const VOLUNTEER_USER_CALL_REQUEST = 'VOLUNTEER_USER_CALL_REQUEST';
export const VOLUNTEER_USER_CALL_SUCCESS = 'VOLUNTEER_USER_CALL_SUCCESS';
export const ORGANISATION_USER_CALL_FAILURE = 'ORGANISATION_USER_CALL_FAILURE';
export const ORGANISATION_USER_CALL_REQUEST = 'ORGANISATION_USER_CALL_REQUEST';
export const ORGANISATION_USER_CALL_SUCCESS = 'ORGANISATION_USER_CALL_SUCCESS';
